navsat_transform_node:
  ros__parameters:
    frequency: 5.0
    delay: 1.0
    magnetic_declination_radians: 0.07  # 0.7 For Montreal
    yaw_offset: 0.0  # IMU reads 0 facing magnetic north, not east
    debug: true
    zero_altitude: true
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false
    use_local_cartesian: false
    broadcast_cartesian_transform: false
    broadcast_cartesian_transform_as_parent_frame: false